### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by Grandzxw** [Jichao-Peng/VINS-Mono-Optimization#1]
请问要用小觅相机跑的话，需要加哪些参数文件和参数啊?

**Comment by boxuLibrary** [comment]
不好意思，我想请教下，您线特征后端优化，对四元数四个参数都在进行更新，这个是过参数表示，会不会导致后端不稳定。

**Comment by ltr-w** [comment]
想问一下，作者的代码你们跑通了吗？我运行的时候[line_feature_tracker-1] process has died ，这个进程总是启动不了

**Comment by xubogithub** [comment]
可以跑通，只是后端进行线特征优化还是有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ltr-w"<notifications@github.com&gt;; 
发送时间: 2019年11月11日(星期一) 下午5:21
收件人: "Jichao-Peng/VINS-Mono-Optimization"<VINS-Mono-Optimization@noreply.github.com&gt;; 
抄送: "徐博"<2816955252@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Jichao-Peng/VINS-Mono-Optimization] 问题咨询 (#1)




想问一下，作者的代码你们跑通了吗？我运行的时候[line_feature_tracker-1] process has died ，这个进程总是启动不了

**Comment by ltr-w** [comment]
请问一下，您是作者的代码直接下载下来不用修改代码就可以跑通吗？您的电脑环境是怎样的？

**Comment by Grandzxw** [comment]
> 请问一下，您是作者的代码直接下载下来不用修改代码就可以跑通吗？您的电脑环境是怎样的？
跑数据集没问题

**Comment by Grandzxw** [comment]
> 不好意思，我想请教下，您线特征后端优化，对四元数四个参数都在进行更新，这个是过参数表示，会不会导致后端不稳定。

可以交流下

**Comment by lisilin013** [comment]
> 请问要用小觅相机跑的话，需要加哪些参数文件和参数啊?

我想你可能需要仿照着vins对应的原本配置，修改你的配置文件。

**Comment by lisilin013** [comment]
> > 不好意思，我想请教下，您线特征后端优化，对四元数四个参数都在进行更新，这个是过参数表示，会不会导致后端不稳定。
> 
> 可以交流下

你好，

> 不好意思，我想请教下，您线特征后端优化，对四元数四个参数都在进行更新，这个是过参数表示，会不会导致后端不稳定。

你好，在程序中我们是用ceres进行优化，和vins相同，比如四元数，存储是使用4个参数，但是优化的时候是按照真实的3个维度进行优化的。

> > 请问一下，您是作者的代码直接下载下来不用修改代码就可以跑通吗？您的电脑环境是怎样的？
> > 跑数据集没问题

你好，电脑配置是ubuntu16.04
ROS Kinetic

**Comment by lisilin013** [comment]
> > 请问一下，您是作者的代码直接下载下来不用修改代码就可以跑通吗？您的电脑环境是怎样的？
> > 跑数据集没问题

ubuntu 16.04
ros kinetic
不需要修改代码，如果需要适配你自己的传感器，修改对应的配置文件参数就可以。

**Comment by lisilin013** [comment]
> 不好意思，我想请教下，您线特征后端优化，对四元数四个参数都在进行更新，这个是过参数表示，会不会导致后端不稳定。

你好，我们是使用ceres进行优化，如同vins一样使用四元数进行存储，但是优化仍然是在三个维度进行优化。可以参看https://github.com/Jichao-Peng/VINS-Mono-Optimization/blob/6f41202c31e454fd5fa899e0c1c8dd1e477af3b1/line_vins_estimator/src/factor/line_projection_factor.cpp#L144
里面的内容，虽然使用了5列，但是优化结果第4列为0
