### ISSUE TITLE
加上摄像头之后，line_vins_estimator运行一会进程就死掉了

### ISSUE THREAD

**Issue by ltr-w** [Jichao-Peng/VINS-Mono-Optimization#2]
大佬有没有加上传感器在真实的环境中运行过？我用d435i和小觅都会遇到问题，具体错误：
levenberg_marquardt_strategy.cc:114] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
 Check failed: size == existing_size Tried adding a parameter block with the same double pointer, 0x9ac538, twice, but with different block sizes. Original size was 9 but new size is 7
*** Check failure stack trace: ***
[line_vins_estimator-2] process has died [pid 14576, exit code -6, cmd /home/lu/pl_vinmono_ws/devel/lib/line_vins_estimator/line_vins_estimator __name:=line_vins_estimator __log:=/home/lu/.ros/log/46b28510-0c3d-11ea-aa37-5cf9dd5ef118/line_vins_estimator-2.log].
log file: /home/lu/.ros/log/46b28510-0c3d-11ea-aa37-5cf9dd5ef118/line_vins_estimator-2*.log

**Comment by Grandzxw** [comment]
> 大佬有没有加上传感器在真实的环境中运行过？我用d435i和小觅都会遇到问题，具体错误：
> levenberg_marquardt_strategy.cc:114] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
> Check failed: size == existing_size Tried adding a parameter block with the same double pointer, 0x9ac538, twice, but with different block sizes. Original size was 9 but new size is 7
> *** Check failure stack trace: ***
> [line_vins_estimator-2] process has died [pid 14576, exit code -6, cmd /home/lu/pl_vinmono_ws/devel/lib/line_vins_estimator/line_vins_estimator __name:=line_vins_estimator __log:=/home/lu/.ros/log/46b28510-0c3d-11ea-aa37-5cf9dd5ef118/line_vins_estimator-2.log].
> log file: /home/lu/.ros/log/46b28510-0c3d-11ea-aa37-5cf9dd5ef118/line_vins_estimator-2*.log

我也是碰到这种情况

**Comment by lisilin013** [comment]
目测是ceres求解错误。

我们没有在实际传感器上进行测试，您可否提供更详细一点信息？
可否传一个数据的rosbag和您的配置文件？
