### ISSUE TITLE
对优化公式的疑惑

### ISSUE THREAD

**Issue by ycdfwzy** [Jichao-Peng/VINS-Mono-Optimization#3]
请问`line_vins_estimator/src/factorline_projection_factor.cpp`的第109行为什么是单位矩阵，按照论文里不应该是投影矩阵K吗？
@lisilin013 @Jichao-Peng 
![Screenshot from 2020-04-25 00-49-37](https://user-images.githubusercontent.com/23055038/80237081-b21dd900-868e-11ea-8566-717003d7ec77.png)

**Comment by lisilin013** [comment]
![Screenshot from 2020-04-25 09-05-11](https://user-images.githubusercontent.com/20241934/80267507-f8495b80-86d3-11ea-80f8-7f7594cbc56c.png)

Reference: PL-VIO: Tightly-Coupled Monocular Visual–Inertial Odometry Using Point and Line Features. Yijia He.

**Comment by lisilin013** [comment]
也可以参看Yijia He大佬前段时间开源的PLVIO中和我们项目中相同的这一段程序。

https://github.com/HeYijia/PL-VIO/blob/ddec7f3995cae0c90ba216861ad7cd784e7004cf/vins_estimator/src/factor/line_projection_factor.cpp#L37

**Comment by ycdfwzy** [comment]
谢谢
