### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by xinyangrobotic** [Jichao-Peng/VINS-Mono-Optimization#4]
Hi, Thank you so much for your open-source code!

I met a problem with compiling. When I ran `catkin_make`, I would see the warning like that:
`[ 73%] Building CXX object VINS-Mono-Optimization/line_vins_estimator/CMakeFiles/line_vins_estimator.dir/src/utility/utility.cpp.o
/usr/bin/ld: warning: libopencv_imgproc3.so.3.3, needed by /root/project/vins_line/src/VINS-Mono-Optimization/line_feature_tracker/line_descriptor/lib/liblinedesc.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_core3.so.3.3, needed by /root/project/vins_line/src/VINS-Mono-Optimization/line_feature_tracker/line_descriptor/lib/liblinedesc.so, not found (try using -rpath or -rpath-link)
[ 73%] Built target line_feature_tracker
[ 74%] Building CXX object VINS-Mono-Optimization/line_vins_estimator/CMakeFiles/line_vins_estimator.dir/src/utility/visualization.cpp.o
`

And when I ran `roslaunch line_vins_estimator euroc_line.launch`, I would see the error like that:
`setting /run_id to c3055fb4-aeb5-11ea-acc1-0242ac110002
process[rosout-1]: started with pid [2021]
started core service [/rosout]
process[line_feature_tracker-2]: started with pid [2024]
/root/project/vins_line/devel/lib/line_feature_tracker/line_feature_tracker: error while loading shared libraries: libopencv_imgproc3.so.3.3: cannot open shared object file: No such file or directory
[line_feature_tracker-2] process has died [pid 2024, exit code 127, cmd /root/project/vins_line/devel/lib/line_feature_tracker/line_feature_tracker __name:=line_feature_tracker __log:=/root/.ros/log/c3055fb4-aeb5-11ea-acc1-0242ac110002/line_feature_tracker-2.log].
log file: /root/.ros/log/c3055fb4-aeb5-11ea-acc1-0242ac110002/line_feature_tracker-2*.log
process[line_vins_estimator-3]: started with pid [2029]
[ WARN] [1592190632.112707420]:  fix extrinsic param 
[ WARN] [1592190632.122117095]: waiting for image and imu...
process[pose_graph-4]: started with pid [2030]
process[rvizvisualisation-5]: started with pid [2037]
process[benchmark_publisher-6]: started with pid [2038]
`

Is that because the wrong version of my OpenCV? May I know what the OpenCV version of yours? 
Thanks again!

**Comment by xinyangrobotic** [comment]
I have solve it. That is because the OpenCV version of my system is 3.2.0, but your line_descriptor version is 3.3.0. I just used the contribs of OpenCV 3.2.0 instead of your line_descriptor and modified some code, it works. Thanks again for your contribution!

**Comment by xiaozhi12345678** [comment]
您好，可以给一个联系方式吗，我也遇到了这个问题，能不能告诉我一下该怎么解决呢

**Comment by xinyangrobotic** [comment]
> 您好，可以给一个联系方式吗，我也遇到了这个问题，能不能告诉我一下该怎么解决呢

wechat:hnlyzxy
